version: '3.8'

networks:
  my_network:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - my_network

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - my_network
    depends_on:
      - mongodb

  dev-client:
    build:
      context: .  # Assure-toi que le code NestJS est dans ./backend
      dockerfile: Dockerfile  # Ton Dockerfile pour NestJSd

    container_name: nestjs_dev_server
    restart: always
    ports:
      - "5000:5000"  # Port par défaut pour NestJS
    volumes:
      - ./:/app  # Monte le code source local pour hot-reloading
      - /app/node_modules  # Ignore node_modules pour éviter les conflits
    networks:
      - my_network
    depends_on:
      - mongodb  # S'assure que MongoDB est prêt avant de lancer NestJS



volumes:
  mongodb_data:
    driver: local
