version: '3.8'

networks:
  my_network:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - my_network

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      
    networks:
      - my_network
    depends_on:
      - mongodb


  dev-client:
    build:
      context: ./  # Ensure the NestJS code is in ./backend
      dockerfile: Dockerfile  # Your NestJS Dockerfile

    container_name: nestjs_dev_server
    restart: always
    ports:
      - "5000:5000"  # Default port for NestJS
    volumes:
      - ./:/app  # Mount the backend code for hot-reloading
      - /app/node_modules  # Prevent node_modules conflicts
    networks:
      - my_network
    depends_on:
      - mongodb  # Ensure MongoDB is ready before launching NestJS

volumes:
  mongodb_data:
    driver: local
